#!/usr/bin/env bash
#Nginx as Nginx
pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
service nginx reload
service nginx restart