#!/usr/bin/env bash
#transsfering files from locate to remote

if[ "$#" -lt 4]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    file="$1"
    host="$2"
    username="$3"
    key="$4"
    scp -i "$key" -o StrictHostKeyChecking=no "$file" "$username@$host:~/"
fi