#!/usr/bin/env bash
#transsfering files from locate to remote

if[ "$#" -lt 4]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -o StrictHostKeyChecking=no -i "$1" "$2@$3":~/
fi