#!/usr/bin/env bash
#resdirecte to pages not found
sudo apt-get -y install nginx
sudo servicde nginx start
pages = "\\\trewrite ^/redirect_me https://voiranime.com/ permanent"
sudo sed -i "53i  $pages" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload